import type { Metadata } from "next";
import { gilroy } from "./fonts/fonts";

import "./global/styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da" className={gilroy.variable}>
      <body>
      <header className="fullbleed"><p>I am header! :D</p></header>
      {children}
      <footer className="fullbleed">´<p>I am footer! :D</p></footer>
      </body>
    </html>
  );
}
