import type { Metadata } from "next";
import { gilroy } from "./fonts/fonts";
import Providers from "./global/utils/Providers";
import Menu from "./global/components/Menu";
import "./global/styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da" className={gilroy.variable}>
      <body>
        <Providers>
      <header className="fullbleed"><p>I am header! :D</p></header>
      {children}
      <Menu></Menu>
        </Providers>
      </body>
    </html>
  );
}
